version: '3.8'

services:
  productmanagementapi:
    image: hao2003/productmanagementapi:latest
    build:
      context: .
      dockerfile: SE172788.ProductManagement.API/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_CONNECTION_STRING=Server=db;Database=ProductManagement;User=sa;Password=Haohaohao123;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Haohaohao123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
